apiVersion: v1
kind: Service
metadata:
  name: gitops-secrets-service
  namespace: argo-secrets
spec:
  type: NodePort
  selector:
    app: gitops-secrets-app
  ports:
      - nodePort: 31300
        protocol: TCP
        port: 8080